# Generated by Django 5.1.3 on 2024-12-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_like_unique_together_remove_like_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='founders/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
