# Generated by Django 5.1.3 on 2024-12-12 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='founder',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='founder',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='founder',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='founders_photos/'),
        ),
    ]
